# vim:syntax=dockerfile

FROM alpine:latest

ADD .stack-work/install/x86_64-linux/lts-6.0/7.10.3/bin /usr/local/bin

# if you need additional system packages add them
# here, or if you build a static application you
# can remove all the apk-add command.
RUN apk update                      \
    && apk add gmp                  \
    && adduser -D -u1000 haskell

USER haskell

WORKDIR /home/haskell

CMD hello-world
